---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: caddy
  labels:
    app: caddy
spec:
  minReadySeconds: 5
  replicas: 1
  selector:
    matchLabels:
      app: cappy
  strategy:
    rollingUpdate: 
      maxSurge: 50%
      maxUnavailable: 50%
  template:
    metadata:
      name: caddy
      labels:
        app: cappy
    spec:
      containers: 
        - name: webapplications
          image: syedsohail321/spc-mvn-3.9.4:1.0
          ports:
            - containerPort: 8080
              protocol: TCP
          # resources:
          #   limits:
          #     memory: "128Mi"
          #     cpu: "500m"
          #   requests:
          #     cpu: "250m"
          #     memory: "64Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: cappy
  labels:
    app: cappy 
spec:
  selector:
    app: cappy
  type: LoadBalancer
  ports:
    - name: caddy-svc
      port: 80
      targetPort: 8080
      protocol: TCP
  















