---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: caddy
  labels:
    app: caddy
spec:
  minReadySeconds: 5
  replicas: 3
  selector:
    matchLabels:
      app: cappy
  strategy:
    rollingUpdate: 
      maxSurge: 50%
      maxUnavailable: 50%
  template:
    metadata:
      name: caddy
      labels:
        app: cappy
    spec:
      containers: 
        - name: webapplications
          image: caddy
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              cpu: "250m"
              memory: "64Mi"

---
apiVersion: apps/v1
kind: Service
metadata:
  name: caddy
  labels:
    app: caddy 
spec:
  selector:
    app: cappy
  type: LoadBalancer
  ports:
    - name: caddy-svc
      port: 80
      targetPort: 80
      protocol: TCP
  















